// examples/create-vue-project/routes/nested-example/layout.tsx
import React from "https://npm.tfl.dev/react";
import { toDist } from "https://tfl.dev/@truffle/distribute@^1.0.0/format/wc/index.ts";

function NestedExampleLayout({ children }) {
  return (
    <>
      This is a layout that applies to all nested children
      {children}
    </>
  );
}

export default toDist("react", NestedExampleLayout, import.meta.url);

// examples/create-react-project/routes/nested-example/layout.tsx
import { component } from 'https://npm.tfl.dev/haunted@5.0.0?bundle';
import { html, unsafeStatic } from "https://npm.tfl.dev/lit-html@2/static";

function NestedExampleLayout({ children }) {
  return html`
    This is a layout that applies to all nested children
    ${children}
  `
}

// export default toWebComponent(NestedExampleLayout)

const elementName = "truffle-layout";
customElements.define(elementName, component(NestedExampleLayout));
export default elementName
