// npm/sdk/examples/vue-basic/src/components/EmbedController.vue
<script setup lang="ts">
import { getEmbed } from '@trufflehq/sdk';
import { reactive } from 'vue';

const embed = getEmbed();

const state = reactive({
  hasBorder: false,
  isSmall: true,
});

const toggleBorder = () => {
  if (state.hasBorder) {
    embed.setStyles({
      border: 'none',
    });
    state.hasBorder = false;
  } else {
    embed.setStyles({
      border: '5px solid red',
    });
    state.hasBorder = true;
  }
};

const toggleSize = () => {
  if (state.isSmall) {
    embed.setStyles({
      width: '800px',
      height: '800px',
    });
    state.isSmall = false;
  } else {
    embed.setStyles({
      width: '600px',
      height: '600px',
    });
    state.isSmall = true;
  }
};
</script>

<template>
  <div>
    <h2>Embed controls</h2>
    <button @click="toggleBorder">Toggle border</button>
    <button @click="toggleSize">Toggle size</button>
  </div>
</template>

// npm/sdk/examples/next-basic/src/components/embed-controller.tsx
import { getEmbed } from '@trufflehq/sdk';
import { useRef } from 'react';

export default function EmbedController() {
  const hasBorder = useRef(false);

  const toggleBorder = () => {
    // Get the embed instance
    const embed = getEmbed();

    if (hasBorder.current) {
      // clear the border
      embed.setStyles({ border: 'none' });
    } else {
      // set the border
      embed.setStyles({ border: '5px solid #f00' });
    }
    hasBorder.current = !hasBorder.current;
  };

  return (
    <div className="c-embed-controller">
      <h2>Embed Controller</h2>
      <div>
        <button onClick={toggleBorder}>Toggle border</button>
      </div>
    </div>
  );
}
